"""baseline — the schema as it stood when git owned proof content

Revision ID: 0001_baseline
Revises:
Create Date: generated from app/db.py's init_db() executescript

FROZEN. Do not edit this file to add or change a column — it is the historical
state every database passes through. Editing it would make a fresh database
diverge from a migrated one, which is the exact drift the migration framework
exists to prevent. New schema changes go in a NEW revision.

Every statement is `create table if not exists`, so this is a no-op against the
pre-existing database (which had these 10 tables at user_version=0 with real
data) and builds the schema from scratch on a fresh one. That is deliberate: a
brand-new database walks the SAME revision chain as a year-old one, so the two
cannot drift.

Statements are applied one at a time via op.execute(). NOT executescript() —
that issues a COMMIT before running, which would silently break the enclosing
per-revision transaction (measured: in_transaction flips True->False and the
rollback then errors "no transaction is active").
"""

from alembic import op

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None

# Extracted verbatim from db.py's init_db(); comments are the schema's docs.
STATEMENTS = [
    """\
            -- No stored `status`: a session's status IS its working-copy verdict
            -- (D14/P2) = the latest code_step's check_status, derived on read so it
            -- can never drift. Run lifecycle (running/done/failed) lives on runs.status.
            create table if not exists sessions (
                id text primary key,
                project_id text references projects(id),
                title text not null,
                api_session_id text,
                -- Session origin / providence (P-origin): where this formalization was
                -- spawned from. 'ui' = the interactive Lea UI (default); 'overleaf' =
                -- the Overleaf extension. `origin_url` is the canonical Overleaf
                -- document URL for an Overleaf-originated session (NULL otherwise), so
                -- the UI can open/focus the source document. Deliberately stored on the
                -- session — NOT on `projects` — so it stays independent of the future
                -- projects feature that owns that table.
                origin text not null default 'ui',
                origin_url text,
                created_at text not null,
                updated_at text not null
            );
    """,
    """\
            -- A project is a shared dir + git repo + this index row (D21). The DB
            -- never stores Instructions/Memory/Blueprint content — those are the
            -- three canonical `.lea/*.md` files (D25/D26/D28); only short metadata
            -- lives here. `slug` is immutable (the durable Overleaf/project binding,
            -- D22). `namespace`/`repo_path` are cached identity fields; Overleaf
            -- project-name changes can migrate them through the explicit rename flow.
            create table if not exists projects (
                id text primary key,
                slug text not null unique,        -- immutable binding, never renamed
                title text not null,
                description text,                  -- short metadata for the project list/cards
                namespace text not null,          -- cached 'Lea.<Project>' (derivable; cached)
                repo_path text not null,          -- 'proofs/Lea/<Project>' — the shared dir/repo (D22)
                remote_url text,                  -- per-project GitHub remote for push (D34; nullable)
                created_at text not null,
                updated_at text not null
            );
    """,
    """\
            -- Uploaded/extracted project files (D27). Index only: the bytes live in
            -- the project repo under `.lea/files/` (git-canonical). `kind` tags the
            -- role; `extracted_path` points at the tiered text sidecar when present.
            create table if not exists project_files (
                id text primary key,
                project_id text not null references projects(id),
                filename text not null,
                stored_path text not null,        -- path within the project repo (.lea/files/<name>)
                mime text,
                kind text not null default 'upload',   -- 'upload' | 'blueprint' | 'extract'
                extracted_path text,              -- tiered text sidecar (.lea/files/<name>.txt)
                created_at text not null
            );
    """,
    """\
            -- A skill is a DB row, NOT a git file (D45) — the deliberate exception
            -- to "git owns content" (D7/D8): skills are small user-authored prose
            -- (markdown `body` in a column), not diffed proof bytes, so they live
            -- here. `slug` is the stable identifier AND the materialized filename
            -- stem (the prover reads `## Skill: <slug>`), so it's unique. `is_global`
            -- = 1 → the skill applies to every project; 0 → only the projects in the
            -- `skill_projects` join (D47; loose sessions get neither). `source_url`/
            -- `source_ref` record GitHub provenance for a later re-sync (D56).
            create table if not exists skills (
                id text primary key,
                name text not null,
                slug text not null unique,
                body text not null,
                is_global integer not null default 0,
                source_url text,
                source_ref text,
                created_at text not null,
                updated_at text not null
            );
    """,
    """\
            -- Per-project assignment for non-global skills (D47). Only meaningful
            -- when the skill's `is_global` = 0; a row means "this skill applies to
            -- this project". Deleting a skill cascades these rows (explicit, in
            -- store.py — SQLite FKs aren't enforced here).
            create table if not exists skill_projects (
                skill_id text not null references skills(id),
                project_id text not null references projects(id),
                primary key (skill_id, project_id)
            );
    """,
    """\
            create table if not exists runs (
                id text primary key,
                session_id text not null references sessions(id),
                project_id text references projects(id),
                status text not null,
                -- Autonomous run (D19): 1 → no per-tool approval gate AND the
                -- non-interactive `default` prompt variant, so the run formalizes
                -- end-to-end with zero human interaction (the Overleaf path). 0 →
                -- the interactive UI behavior (gated tools + collaborator prompt).
                -- Set at create time from the request; read back when the SSE
                -- stream spawns the run thread (a separate HTTP request).
                autonomous integer not null default 0,
                api_run_id text,
                pending_approval text,
                model text not null,
                provider text,
                max_turns integer,
                input_tokens integer default 0,
                output_tokens integer default 0,
                cost_usd real not null default 0,
                final_text text,
                result_kind text,
                result_detail text,
                -- The faithful prover conversation at this run's end (JSON list of
                -- messages, with tool_call/tool_result parts) — the model-replay
                -- transcript fed to the next activation for multi-turn (D16). Distinct
                -- from the display `messages` table, which is the flattened human thread.
                -- NULL until the run produces a Finished event (errored runs store none).
                transcript text,
                safe_verify_status text,
                safe_verify_detail text,
                created_at text not null,
                updated_at text not null
            );
    """,
    """\
            -- A transcript message. `kind='edit_note'` is a user's explanation of a
            -- canvas edit (D11), linked to that edit's git commit via commit_sha — a
            -- normal message, no bespoke channel. The CHECK enforces D11 at the source:
            -- an edit_note must carry a commit_sha (other kinds leave it NULL).
            create table if not exists messages (
                id text primary key,
                session_id text not null references sessions(id),
                run_id text references runs(id),
                role text not null,
                content text not null,
                kind text not null default 'assistant',
                commit_sha text,
                seq integer not null,                     -- shared per-session timeline position (C4)
                created_at text not null,
                check (kind <> 'edit_note' or commit_sha is not null)
            );
    """,
    """\
            -- A curated step in the session timeline. v2 (D7/D8): git owns the
            -- proof *content*, so a row is a pointer (commit_sha + path) into the
            -- session's git repo plus presentation metadata — not the file text.
            create table if not exists code_steps (
                id text primary key,
                session_id text not null references sessions(id),
                run_id text references runs(id),          -- NULL for user edits (D9)
                seq integer not null,                     -- shared per-session timeline position (C4)
                turn integer,                             -- agent turn; NULL for user edits
                author text not null default 'agent',     -- 'agent' | 'user' | 'cascade' (free-text convention, no CHECK)
                path text not null,                       -- file this step shows
                commit_sha text not null,                 -- pointer into the git repo (the content)
                summary text,                             -- short label / narration
                check_status text,                        -- 'ok' | 'error' | 'unchecked' (D6)
                check_detail text,                        -- first error line (nullable)
                artifact_kind text,                       -- 'proof' | 'definition' | 'mixed' | 'unknown' when check_status='ok'
                created_at text not null
            );
    """,
    """\
            create table if not exists status_events (
                id text primary key,
                session_id text not null references sessions(id),
                run_id text not null references runs(id),
                step_number integer,
                status text,
                message text not null,
                created_at text not null
            );
    """,
    """\
            create table if not exists run_usage_breakdown (
                id text primary key,
                session_id text not null references sessions(id),
                run_id text not null references runs(id),
                run_number integer not null,
                ordinal integer not null,
                phase text not null,
                label text not null,
                turn integer,
                candidate integer,
                input_tokens integer not null default 0,
                output_tokens integer not null default 0,
                cost_usd real not null default 0,
                event_count integer not null default 0,
                created_at text not null
            );
    """,
]


def upgrade() -> None:
    for statement in STATEMENTS:
        op.execute(statement)


def downgrade() -> None:
    # Deliberately not implemented. Downgrading the baseline means dropping every
    # table — i.e. destroying the database this framework exists to protect. Use a
    # backup, not a downgrade.
    raise NotImplementedError("the baseline revision is not reversible")
